/* generated by Svelte v3.24.0 */
import {
	SvelteComponent,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space
} from "/svelte/internal.js";

function create_fragment(ctx) {
	let h2;
	let t1;
	let p0;
	let t3;
	let blockquote;
	let t5;
	let pre;

	let raw_value = `
<code class="language-js"><span class="token comment">// 🤔 where do I find &#96;some-location&#96;</span>
<span class="token keyword">import</span> someModule <span class="token keyword">from</span> <span class="token string">'some-location'</span><span class="token punctuation">;</span></code>` + "";

	return {
		c() {
			h2 = element("h2");
			h2.textContent = "📚 Recap on module resolution & installation";
			t1 = space();
			p0 = element("p");
			p0.innerHTML = `<strong>Module Resolution</strong>`;
			t3 = space();
			blockquote = element("blockquote");
			blockquote.innerHTML = `<p>is to figure out where 🤬 is your module you are importing</p>`;
			t5 = space();
			pre = element("pre");
			attr(pre, "class", "language-js");
		},
		m(target, anchor) {
			insert(target, h2, anchor);
			insert(target, t1, anchor);
			insert(target, p0, anchor);
			insert(target, t3, anchor);
			insert(target, blockquote, anchor);
			insert(target, t5, anchor);
			insert(target, pre, anchor);
			pre.innerHTML = raw_value;
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(h2);
			if (detaching) detach(t1);
			if (detaching) detach(p0);
			if (detaching) detach(t3);
			if (detaching) detach(blockquote);
			if (detaching) detach(t5);
			if (detaching) detach(pre);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;