/* generated by Svelte v3.24.0 */
import {
	SvelteComponent,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space
} from "/svelte/internal.js";

function create_fragment(ctx) {
	let h2;
	let t1;
	let blockquote;

	return {
		c() {
			h2 = element("h2");
			h2.textContent = "♻ Installation";
			t1 = space();
			blockquote = element("blockquote");
			blockquote.innerHTML = `<p>👨‍⚕️ kinda reverse engineer of module resolution, and you can be innovative about it</p>`;
		},
		m(target, anchor) {
			insert(target, h2, anchor);
			insert(target, t1, anchor);
			insert(target, blockquote, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(h2);
			if (detaching) detach(t1);
			if (detaching) detach(blockquote);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;