/* generated by Svelte v3.24.0 */
import {
	SvelteComponent,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space
} from "/svelte/internal.js";

function create_fragment(ctx) {
	let h2;
	let t1;
	let p;
	let t3;
	let ul;

	return {
		c() {
			h2 = element("h2");
			h2.textContent = "📦 Modules";
			t1 = space();
			p = element("p");
			p.textContent = "A JS module has the following capabilities:";
			t3 = space();
			ul = element("ul");

			ul.innerHTML = `<li>Able to export functionality</li> 
<li>Able to import functionality from another module</li> 
<li>…and a few interesting quirks 🙈</li>`;
		},
		m(target, anchor) {
			insert(target, h2, anchor);
			insert(target, t1, anchor);
			insert(target, p, anchor);
			insert(target, t3, anchor);
			insert(target, ul, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(h2);
			if (detaching) detach(t1);
			if (detaching) detach(p);
			if (detaching) detach(t3);
			if (detaching) detach(ul);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;