/* generated by Svelte v3.24.0 */
import {
	SvelteComponent,
	attr,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	noop,
	safe_not_equal,
	space,
	transition_in,
	transition_out
} from "/svelte/internal.js";

import Folder from "/components/Folder.js";
import toFolder from "/components/toFolder.js";
import Notes from "/components/Notes.js";

function create_fragment(ctx) {
	let h2;
	let t2;
	let folder_1;
	let t3;
	let pre;

	let raw_value = `
<code class="language-js"><span class="token comment">// filename: webpack.config.js</span>

module<span class="token punctuation">.</span>exports <span class="token operator">=</span> <span class="token punctuation">&#123;</span>
  resolve<span class="token operator">:</span> <span class="token punctuation">&#123;</span>
    symlinks<span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span>
    modules<span class="token operator">:</span> <span class="token punctuation">[</span>
      <span class="token string">'node_modules'</span><span class="token punctuation">,</span>
      <span class="token string">'/shopee/node_modules'</span><span class="token punctuation">,</span>
    <span class="token punctuation">]</span><span class="token punctuation">,</span>
    plugins<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token keyword">new</span> <span class="token class-name">IfPeerSkipDevDependencyPlugin</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
  <span class="token punctuation">&#125;</span>
<span class="token punctuation">&#125;</span></code>` + "";

	let current;
	folder_1 = new Folder({ props: { folder: /*folder*/ ctx[0] } });

	return {
		c() {
			h2 = element("h2");
			h2.innerHTML = `🐛 Solution #2: <code>symlinks: false</code>`;
			t2 = space();
			create_component(folder_1.$$.fragment);
			t3 = space();
			pre = element("pre");
			attr(pre, "class", "language-js");
		},
		m(target, anchor) {
			insert(target, h2, anchor);
			insert(target, t2, anchor);
			mount_component(folder_1, target, anchor);
			insert(target, t3, anchor);
			insert(target, pre, anchor);
			pre.innerHTML = raw_value;
			current = true;
		},
		p: noop,
		i(local) {
			if (current) return;
			transition_in(folder_1.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(folder_1.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(h2);
			if (detaching) detach(t2);
			destroy_component(folder_1, detaching);
			if (detaching) detach(t3);
			if (detaching) detach(pre);
		}
	};
}

function instance($$self) {
	const folder = toFolder`
+ shopee
+ packages
  + checkout-page
    + node_modules
      + payment-utils --> ../../payment-utils
        - index.js # import 'crypto-js';
      - crypto-js
  + payment-utils
    - index.js # import 'crypto-js';
`;

	return [folder];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Component;