/* generated by Svelte v3.24.0 */
import {
	SvelteComponent,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	noop,
	safe_not_equal,
	space,
	transition_in,
	transition_out
} from "/svelte/internal.js";

import Notes from "/components/Notes.js";

function create_fragment(ctx) {
	let h2;
	let t1;
	let ul;
	let t10;
	let notes;
	let current;

	notes = new Notes({
			props: {
				note: "\n2 general idea\n- symlink\n- hoisting\n"
			}
		});

	return {
		c() {
			h2 = element("h2");
			h2.textContent = "♻ Installation";
			t1 = space();
			ul = element("ul");

			ul.innerHTML = `<li>lerna + npm</li> 
<li>lerna + npm + <code>hoisting: true</code></li> 
<li>lerna + yarn</li> 
<li>lerna + yarn workspace</li>`;

			t10 = space();
			create_component(notes.$$.fragment);
		},
		m(target, anchor) {
			insert(target, h2, anchor);
			insert(target, t1, anchor);
			insert(target, ul, anchor);
			insert(target, t10, anchor);
			mount_component(notes, target, anchor);
			current = true;
		},
		p: noop,
		i(local) {
			if (current) return;
			transition_in(notes.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(notes.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(h2);
			if (detaching) detach(t1);
			if (detaching) detach(ul);
			if (detaching) detach(t10);
			destroy_component(notes, detaching);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;